# Site settings
title: Learning something new every day
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "http://dev.srdanstanic.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-91990229-1
disqus_shortname: dev-srdanstanic-com
